---
apiVersion: v1
kind: Service
metadata:
  # This used to be php-utility-service to be better distinguishable, but a suffix of the kind that it is seems redundant. It also determines the cluster domain.
  name: php-utility
spec:
  selector:
    app: php-utility-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
